POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Tom Abramov",
  "number": "12-43-234345"
}

###
POST https://shielded-woodland-51742.herokuapp.com/api/persons
Content-Type: application/json

{
  "number": "12-43-234345"
}

###
POST https://shielded-woodland-51742.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Dan Abramov"
}

###
DELETE https://shielded-woodland-51742.herokuapp.com/api/persons/75956

###
GET https://shielded-woodland-51742.herokuapp.com/api/persons