POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Luke",
  "number": "12-234345"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "12-43-234345"
}

###
POST https://shielded-woodland-51742.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Dan Abramov",
  "number": 423
}

###
DELETE https://shielded-woodland-51742.herokuapp.com/api/persons/75956

###
GET https://shielded-woodland-51742.herokuapp.com/api/persons